services:
 
  redis:
    image: redis:7-alpine
    container_name: cinesaint-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cinesaint-network
 
volumes:
  postgres-data:
  redis-data:
 
networks:
  cinesaint-network:
    driver: bridge